export const SELECCIONAR_CLIENTE = `SELECCIONAR_CLIENTE`
export const SELECCIONAR_PRODUCTO = `SELECCIONAR_PRODUCTO`
export const SELECCIONAR_CANTIDAD_PRODUCTOS = `SELECCIONAR_CANTIDAD_PRODUCTOS`
export const CAMBIAR_NUMERO_A_1 = "CAMBIAR_NUMERO_A_1"