import { Inter } from 'next/font/google'
import './globals.css'
import client from "@/config/apollo"
import {ApolloProvider} from "@apollo/client"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ApolloProvider client={client}>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ApolloProvider>
  )
}
